apiVersion: apps/v1
kind: Deployment
metadata:
  name: mytools
  labels:
    app: mytools
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mytools
  template:
    metadata:
      labels:
        app: mytools
    spec:
      containers:
      - name: mytools
        image: ashokbuttowski/my-tools
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mytools-clusterip-service
spec:
  type: ClusterIP
  selector:
    app: mytools
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
