version: '3.8'
services:
  my-tools:
    image: ashokbuttowski/my-tools
    container_name: my-tools
    ports:
      - "9095:80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3